import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import  Ses  from "@/libs/SessionProvider";
import { getServerSession } from "next-auth";
import  SessionProvider  from "@/libs/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession()
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <div>
            {children}cha
          </div>
        </SessionProvider>
        
      </body>
    </html>
  );
}
